from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns=[
url(r'^$',views.index,name='index'),
url(r'^institute/$',views.institute,name="institute"),
url(r'^Isignup/$',views.ISignup,name="Isignup"),
url(r'^Clogin/$',views.CLogin,name="Clogin"),
url(r'^Student_Login/$',views.Student_Login,name="Student_Login"),
url(r'^ILogin/$',views.ILogin,name="Ilogin"),
url(r'^IHome/$',views.IHome,name="IHome"),
url(r'^StudentHome/$',views.StudentHome,name="StudentHome"),
url(r'^IFaculty/$',views.IFaculty,name="IFaculty"),
url(r'^SFaculty/$',views.SFaculty,name="SFaculty"),
url(r'^IAchive/$',views.IAchive,name="IAchive"),
url(r'^SAchive/$',views.SAchive,name="SAchive"),
url(r'^AddAchive/$',views.AddAchivements,name="AddAchive"),
url(r'^AddFaculty/$',views.AddFacultyProfile,name="AddFaculty"),
url(r'^AddStudents/$',views.AddStudents,name="AddStudents"),
url(r'^IStudents/$',views.IStudents,name="Students"),
url(r'^IBlog/$',views.IBlog,name="Blogs"),
url(r'^SBlog/$',views.SBlog,name="Blogs"),
url(r'^AddBlog/$',views.AddBlogs,name="AddBlogs"),
url(r'^AddTest/$',views.AddTest,name="AddTest"),
url(r'^CreateTest/$',views.GoToTest,name="GoToTest"),
url(r'^QuestionPage/$',views.QuestionsPage,name="QuestionPage"),
url(r'^AddQuestion/$',views.AddQuestion,name="AddQuestion"),
url(r'^Edit_Question/$',views.Edit_Question,name="Edit_Question"),
url(r'^EditTest/$',views.EditTest,name="EditTest"),
url(r'^Edit_Test/$',views.Edit_Test,name="Edit_Test"),
url(r'^Preview/$',views.Preview,name="Preview"),
url(r'^Student_Signup/$',views.Student_Signup,name="Student_Signup"),
url(r'^instituteHome/$',views.instituteHome,name="instituteHome"),
url(r'^TestPaper/$',views.OpenTest,name="OpenTest"),
url(r'^Resume/$',views.Resume,name="Resume"),
url(r'^DeleteTest/$',views.DeleteTest,name="DeleteTest"),
url(r'^DeleteBlog/$',views.DeleteBlog,name="DeleteBlog"),
url(r'^ActiveTest/$',views.ActiveTest,name="ActiveTest"),
url(r'^DeActiveTest/$',views.DeActiveTest,name="DeActiveTest"),
url(r'^FetchPaper/$',views.FetchPaper,name="FetchPaper"),
url(r'^activeI/(?P<key>.*)/$',views.activeI,name="activeI"),
url(r'^activeS/(?P<key>.*)/$',views.activeS,name="activeS"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
