# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default=b'', max_length=100)),
                ('Name', models.CharField(default=b'', max_length=100)),
                ('Comment', models.CharField(default=b'', max_length=200)),
                ('Image', models.FileField(blank=True, upload_to=b'Achivements')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default=b'', max_length=100)),
                ('Title', models.CharField(default=b'', max_length=100)),
                ('Author', models.CharField(default=b'', max_length=100)),
                ('Text', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default=b'', max_length=100)),
                ('Name', models.CharField(default=b'', max_length=100)),
                ('Area', models.CharField(default=b'', max_length=100)),
                ('Experience', models.CharField(default=b'', max_length=100)),
                ('Image', models.FileField(blank=True, upload_to=b'Faculty_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Key', models.CharField(default=b'', max_length=120)),
                ('Varified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_Email', models.CharField(default=b'', max_length=100)),
                ('Student_Email', models.CharField(default=b'', max_length=100)),
                ('Enrollment_No', models.IntegerField(default=0)),
                ('Student_Name', models.CharField(default=b'', max_length=100)),
            ],
        ),
    ]
