# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default='', max_length=100)),
                ('Test_id', models.IntegerField(default=1, max_length=100)),
                ('Test_Name', models.CharField(default=0, max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='achivements',
            name='Comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='Image',
            field=models.FileField(blank=True, upload_to='Achivements'),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Experience',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Image',
            field=models.FileField(blank=True, upload_to='Faculty_Profile'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='Key',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='students',
            name='Institute_Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='Student_Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='Student_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
