# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0002_auto_20170528_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='Test_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tests',
            name='Test_id',
            field=models.IntegerField(default=1),
        ),
    ]
