# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0003_auto_20170528_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='published_date',
            new_name='publish_date',
        ),
    ]
