# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0004_auto_20170528_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default='', max_length=100)),
                ('Test_id', models.IntegerField(default=1)),
                ('Question', models.CharField(default='', max_length=100)),
                ('Correct_Answers', models.CharField(default='', max_length=100)),
                ('Wrongs_Answers', models.CharField(default='', max_length=100)),
                ('Type', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
