# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0005_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Wrongs_Answers',
            new_name='Wrong_Answers',
        ),
    ]
