# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0006_auto_20170530_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Image',
            field=models.FileField(blank=True, upload_to='Questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='Marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='Nmarks',
            field=models.IntegerField(default=0),
        ),
    ]
