# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0007_auto_20170530_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Question_No',
            field=models.IntegerField(default=1),
        ),
    ]
