# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0008_questions_question_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Key', models.CharField(default='', max_length=120)),
                ('Varified', models.BooleanField(default=False)),
            ],
        ),
    ]
