# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0010_tests_no_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Correct_Answers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Wrong_Answers',
            field=models.TextField(default='', max_length=100),
        ),
    ]
