# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0011_auto_20170610_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Question',
            field=models.TextField(default=''),
        ),
    ]
