# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0014_auto_20170621_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='Questions'),
        ),
    ]
