# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayaShala', '0015_auto_20170621_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
    ]
